### PR TITLE
Update kde urls

### PR DESCRIPTION
**Pull request by forivall**
The url to the kde repository was out of date.

Also, it looks like the mirror push hook doesn't run for l10n updates? You should look into that. Cheers :beers:

### CODE REVIEW

**Comment by albertvaka** [comment]
I fixed the links myself tonight. Sorry for not seeing your PR before :/

**Comment by forivall** [comment]
Would you consider adding the CONTRIBUTING.md, since the links to the bugtracker and mailinglist are somewhat tricky to find for an intrepid googler?

**Comment by albertvaka** [comment]
Could you update the PR so it includes just that file? This way I can just merge your commit.

**Comment by forivall** [comment]
Since the PR has been closed, it won't update with new pushes to the branch. New PR at #8.

**Pull request closed without merging**
